const jsonData = {
  ROOT: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#ffffff",
      padding: 5,
      tailwindCss: "h-full",
      "data-cy": "root-container",
    },
    displayName: "Container",
    custom: {},
    hidden: false,
    nodes: ["NoTZHwT-Iq"],
    linkedNodes: {},
  },
  "NoTZHwT-Iq": {
    type: { resolvedName: "TailwindCard" },
    isCanvas: false,
    props: {
      background: "#fef9c3",
      padding: 3,
      tailwindCss:
        "py-8 px-4 mx-auto max-w-screen-xl sm:py-16 lg:px-6 bg-[#fef9c3] dark:bg-gray-900",
    },
    displayName: "TailwindCard",
    custom: {},
    parent: "ROOT",
    hidden: false,
    nodes: [],
    linkedNodes: { heading: "BW7S5yXy86", body: "fw8KO_QXym" },
  },
  BW7S5yXy86: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss: "max-w-screen-md mb-8 lg:mb-16",
    },
    displayName: "Container",
    custom: {},
    parent: "NoTZHwT-Iq",
    hidden: false,
    nodes: ["NblfiC8zRK", "wLOLnwIcde"],
    linkedNodes: {},
  },
  NblfiC8zRK: {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Designed for business teams like yours",
      fontSize: 20,
      tailwindCss:
        "mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white",
    },
    displayName: "Text",
    custom: {},
    parent: "BW7S5yXy86",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  wLOLnwIcde: {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: " Here at Flowbite we focus on markets where technology, innovation, and\n          capital can unlock long-term value and drive economic growth.",
      fontSize: 20,
      tailwindCss: "text-gray-500 sm:text-xl dark:text-gray-400",
    },
    displayName: "Text",
    custom: {},
    parent: "BW7S5yXy86",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  fw8KO_QXym: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss:
        "space-y-8 md:grid md:grid-cols-2 lg:grid-cols-3 md:gap-12 md:space-y-0",
    },
    displayName: "Container",
    custom: {},
    parent: "NoTZHwT-Iq",
    hidden: false,
    nodes: [
      "oi_RVgW428",
      "jwPlr4kQg0",
      "F6MlocRNcW",
      "chuO1_Ivi3",
      "CKNhuHpUqo",
      "h90zVAMBdA",
      "V4zKmonv44",
      "RF90wpOHsv",
    ],
    linkedNodes: {},
  },
  oi_RVgW428: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss: " ",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "fw8KO_QXym",
    hidden: false,
    nodes: ["oIl8qtDVLr", "6SVvxFHC3B", "oHz52KY138"],
    linkedNodes: {},
  },
  oIl8qtDVLr: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss:
        "flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12 dark:bg-primary-900",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "oi_RVgW428",
    hidden: false,
    nodes: ["gk8YCV2FaE"],
    linkedNodes: {},
  },
  "6SVvxFHC3B": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Marketing",
      fontSize: 20,
      tailwindCss: "mb-2 text-xl font-bold dark:text-white",
    },
    displayName: "Text",
    custom: {},
    parent: "oi_RVgW428",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  oHz52KY138: {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "\n            Plan it, create it, launch it. Collaborate seamlessly with all the\n            organization and hit your marketing goals every month with our\n            marketing plan.",
      fontSize: 20,
      tailwindCss: "text-gray-500 dark:text-gray-400",
    },
    displayName: "Text",
    custom: {},
    parent: "oi_RVgW428",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  jwPlr4kQg0: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss: " ",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "fw8KO_QXym",
    hidden: false,
    nodes: ["_XSPdmOCCg", "_2eNeqn3UC", "AVNm3WNECR"],
    linkedNodes: {},
  },
  _XSPdmOCCg: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss:
        "flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12 dark:bg-primary-900",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "jwPlr4kQg0",
    hidden: false,
    nodes: ["qJd6ZM9SiM"],
    linkedNodes: {},
  },
  qJd6ZM9SiM: {
    type: { resolvedName: "ImageSelector" },
    isCanvas: false,
    props: {
      src: "../../png.png",
      alt: "Image",
      width: 200,
      height: 200,
      tailwindCss: "w-10 h-8",
    },
    displayName: "ImageSelector",
    custom: {},
    parent: "_XSPdmOCCg",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  _2eNeqn3UC: {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Marketing",
      fontSize: 20,
      tailwindCss: "mb-2 text-xl font-bold dark:text-white",
    },
    displayName: "Text",
    custom: {},
    parent: "jwPlr4kQg0",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  AVNm3WNECR: {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "\n            Plan it, create it, launch it. Collaborate seamlessly with all the\n            organization and hit your marketing goals every month with our\n            marketing plan.",
      fontSize: 20,
      tailwindCss: "text-gray-500 dark:text-gray-400",
    },
    displayName: "Text",
    custom: {},
    parent: "jwPlr4kQg0",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  F6MlocRNcW: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss: " ",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "fw8KO_QXym",
    hidden: false,
    nodes: ["m8vkbp4bTm", "Nm9uPT-Rjt", "q2k63g9_jH"],
    linkedNodes: {},
  },
  m8vkbp4bTm: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss:
        "flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12 dark:bg-primary-900",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "F6MlocRNcW",
    hidden: false,
    nodes: ["g2PoWNuVa5"],
    linkedNodes: {},
  },
  g2PoWNuVa5: {
    type: { resolvedName: "ImageSelector" },
    isCanvas: false,
    props: {
      src: "../../png.png",
      alt: "Image",
      width: 200,
      height: 200,
      tailwindCss: "w-10 h-8",
    },
    displayName: "ImageSelector",
    custom: {},
    parent: "m8vkbp4bTm",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "Nm9uPT-Rjt": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Marketing",
      fontSize: 20,
      tailwindCss: "mb-2 text-xl font-bold dark:text-white",
    },
    displayName: "Text",
    custom: {},
    parent: "F6MlocRNcW",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  q2k63g9_jH: {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "\n            Plan it, create it, launch it. Collaborate seamlessly with all the\n            organization and hit your marketing goals every month with our\n            marketing plan.",
      fontSize: 20,
      tailwindCss: "text-gray-500 dark:text-gray-400",
    },
    displayName: "Text",
    custom: {},
    parent: "F6MlocRNcW",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  chuO1_Ivi3: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss: " ",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "fw8KO_QXym",
    hidden: false,
    nodes: ["bbz3E3qKeb", "i2S9y1aPh-", "IVRLFTlUQb"],
    linkedNodes: {},
  },
  bbz3E3qKeb: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss:
        "flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12 dark:bg-primary-900",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "chuO1_Ivi3",
    hidden: false,
    nodes: ["Cu6ENGX42F"],
    linkedNodes: {},
  },
  Cu6ENGX42F: {
    type: { resolvedName: "ImageSelector" },
    isCanvas: false,
    props: {
      src: "../../png.png",
      alt: "Image",
      width: 200,
      height: 200,
      tailwindCss: "w-10 h-8",
    },
    displayName: "ImageSelector",
    custom: {},
    parent: "bbz3E3qKeb",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "i2S9y1aPh-": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Marketing",
      fontSize: 20,
      tailwindCss: "mb-2 text-xl font-bold dark:text-white",
    },
    displayName: "Text",
    custom: {},
    parent: "chuO1_Ivi3",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  IVRLFTlUQb: {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "\n            Plan it, create it, launch it. Collaborate seamlessly with all the\n            organization and hit your marketing goals every month with our\n            marketing plan.",
      fontSize: 20,
      tailwindCss: "text-gray-500 dark:text-gray-400",
    },
    displayName: "Text",
    custom: {},
    parent: "chuO1_Ivi3",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  CKNhuHpUqo: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss: " ",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "fw8KO_QXym",
    hidden: false,
    nodes: ["6AbJI6-DLc", "LwV61Z7B9Q", "nSapUJumK1"],
    linkedNodes: {},
  },
  "6AbJI6-DLc": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss:
        "flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12 dark:bg-primary-900",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "CKNhuHpUqo",
    hidden: false,
    nodes: ["pGDiohHe_i"],
    linkedNodes: {},
  },
  pGDiohHe_i: {
    type: { resolvedName: "ImageSelector" },
    isCanvas: false,
    props: {
      src: "../../png.png",
      alt: "Image",
      width: 200,
      height: 200,
      tailwindCss: "w-10 h-8",
    },
    displayName: "ImageSelector",
    custom: {},
    parent: "6AbJI6-DLc",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  LwV61Z7B9Q: {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Marketing",
      fontSize: 20,
      tailwindCss: "mb-2 text-xl font-bold dark:text-white",
    },
    displayName: "Text",
    custom: {},
    parent: "CKNhuHpUqo",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  nSapUJumK1: {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "\n            Plan it, create it, launch it. Collaborate seamlessly with all the\n            organization and hit your marketing goals every month with our\n            marketing plan.",
      fontSize: 20,
      tailwindCss: "text-gray-500 dark:text-gray-400",
    },
    displayName: "Text",
    custom: {},
    parent: "CKNhuHpUqo",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  h90zVAMBdA: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss: " ",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "fw8KO_QXym",
    hidden: false,
    nodes: ["4SMVxS7YUA", "GpFZODiucF", "qVdpcBLss0"],
    linkedNodes: {},
  },
  "4SMVxS7YUA": {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss:
        "flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12 dark:bg-primary-900",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "h90zVAMBdA",
    hidden: false,
    nodes: ["u9bH7NV52P"],
    linkedNodes: {},
  },
  u9bH7NV52P: {
    type: { resolvedName: "ImageSelector" },
    isCanvas: false,
    props: {
      src: "../../png.png",
      alt: "Image",
      width: 200,
      height: 200,
      tailwindCss: "w-10 h-8",
    },
    displayName: "ImageSelector",
    custom: {},
    parent: "4SMVxS7YUA",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  GpFZODiucF: {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Marketing",
      fontSize: 20,
      tailwindCss: "mb-2 text-xl font-bold dark:text-white",
    },
    displayName: "Text",
    custom: {},
    parent: "h90zVAMBdA",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  qVdpcBLss0: {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "\n            Plan it, create it, launch it. Collaborate seamlessly with all the\n            organization and hit your marketing goals every month with our\n            marketing plan.",
      fontSize: 20,
      tailwindCss: "text-gray-500 dark:text-gray-400",
    },
    displayName: "Text",
    custom: {},
    parent: "h90zVAMBdA",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  V4zKmonv44: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss: " ",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "fw8KO_QXym",
    hidden: false,
    nodes: ["tF0OETciot", "9ufi3xAvl2", "hb6FwqJfqN"],
    linkedNodes: {},
  },
  tF0OETciot: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss:
        "flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12 dark:bg-primary-900",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "V4zKmonv44",
    hidden: false,
    nodes: ["QylhHti_VZ"],
    linkedNodes: {},
  },
  QylhHti_VZ: {
    type: { resolvedName: "ImageSelector" },
    isCanvas: false,
    props: {
      src: "../../png.png",
      alt: "Image",
      width: 200,
      height: 200,
      tailwindCss: "w-10 h-8",
    },
    displayName: "ImageSelector",
    custom: {},
    parent: "tF0OETciot",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "9ufi3xAvl2": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Marketing",
      fontSize: 20,
      tailwindCss: "mb-2 text-xl font-bold dark:text-white",
    },
    displayName: "Text",
    custom: {},
    parent: "V4zKmonv44",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  hb6FwqJfqN: {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "\n            Plan it, create it, launch it. Collaborate seamlessly with all the\n            organization and hit your marketing goals every month with our\n            marketing plan.",
      fontSize: 20,
      tailwindCss: "text-gray-500 dark:text-gray-400",
    },
    displayName: "Text",
    custom: {},
    parent: "V4zKmonv44",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  RF90wpOHsv: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss: " ",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "fw8KO_QXym",
    hidden: false,
    nodes: ["STsSOkuv3u", "kjhLxPSMK4", "G1YRSn-mCd"],
    linkedNodes: {},
  },
  STsSOkuv3u: {
    type: { resolvedName: "Container" },
    isCanvas: true,
    props: {
      background: "#00000000",
      padding: 3,
      tailwindCss:
        "flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12 dark:bg-primary-900",
      id: "body",
    },
    displayName: "Container",
    custom: {},
    parent: "RF90wpOHsv",
    hidden: false,
    nodes: ["zQFcsMzAQI"],
    linkedNodes: {},
  },
  zQFcsMzAQI: {
    type: { resolvedName: "ImageSelector" },
    isCanvas: false,
    props: {
      src: "../../png.png",
      alt: "Image",
      width: 200,
      height: 200,
      tailwindCss: "w-10 h-8",
    },
    displayName: "ImageSelector",
    custom: {},
    parent: "STsSOkuv3u",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  kjhLxPSMK4: {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "Marketing",
      fontSize: 20,
      tailwindCss: "mb-2 text-xl font-bold dark:text-white",
    },
    displayName: "Text",
    custom: {},
    parent: "RF90wpOHsv",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  "G1YRSn-mCd": {
    type: { resolvedName: "Text" },
    isCanvas: false,
    props: {
      text: "\n            Plan it, create it, launch it. Collaborate seamlessly with all the\n            organization and hit your marketing goals every month with our\n            marketing plan.",
      fontSize: 20,
      tailwindCss: "text-gray-500 dark:text-gray-400",
    },
    displayName: "Text",
    custom: {},
    parent: "RF90wpOHsv",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  gk8YCV2FaE: {
    type: { resolvedName: "ImageSelector" },
    isCanvas: false,
    props: {
      src: "/png.png",
      alt: "Image",
      width: 200,
      height: 200,
      text: "Hi world",
      tailwindCss: "w-10 h-8",
    },
    displayName: "ImageSelector",
    custom: {},
    parent: "oIl8qtDVLr",
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};
export default jsonData;
